[versions]
android-plugin = "8.5.0"
androidx-annotation = "1.8.0"
publish-plugin = "2.0.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-plugin" }
publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
