name: Build libmpv-android

on:
  push:
    branches:
      - test
  pull_request:

permissions:
  contents: write

env:
  NDK_VER: 26.3.11579264

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (full)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_full.sh
          ./bundle_full.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./output/*
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: "temp"
          tag_name: github.ref
          files: |
            output/*
